#include "project.h"

void boot (uint64_t entry)
{

  __asm__ __volatile__ (
    ".align 16								\n"
    "									\n"
    "	mov %%rax, %%rdi						\n"
    "	call base							\n"
    "base:								\n"
    "	pop %%rsi							\n"
    "									\n"
    "	lea (1f - base) (%%rsi, 1), %%rax				\n"
    "	mov %%eax, (vector - base) (%%rsi, 1)				\n"
    "									\n"
    "	lea (gdt - base) (%%rsi, 1), %%rax				\n"
    "	mov %%rax, (gdtaddr - base) (%%rsi, 1)				\n"
    "									\n"
    "	lidt (idtdesc - base) (%%rsi, 1)				\n"
    "	lgdt (gdtdesc - base) (%%rsi, 1)				\n"
    "									\n"
    "	ljmp *(vector - base) (%%rsi, 1)				\n"
    "									\n"
    "1:									\n"
    "	.code32								\n"
    "									\n"
    "	mov $0x18, %%eax						\n"
    "	mov %%eax, %%ds							\n"
    "	mov %%eax, %%es							\n"
    "	mov %%eax, %%fs							\n"
    "	mov %%eax, %%gs							\n"
    "	mov %%eax, %%ss							\n"
    "									\n"
    "	/* Disable paging. */						\n"
    "	mov %%cr0, %%eax						\n"
    "	and $0x7fffffff, %%eax						\n"
    "	mov %%eax, %%cr0						\n"
    "									\n"
    "	/* Disable amd64. */						\n"
    "	mov $0xc0000080, %%ecx						\n"
    "	rdmsr								\n"
    "	and $0xfffffeff, %%eax						\n"
    "	wrmsr								\n"
    "									\n"
    "	/* Turn off PAE. */						\n"
    "	movl %%cr4, %%eax						\n"
    "	and $0xffffffcf, %%eax						\n"
    "	mov %%eax, %%cr4						\n"
    "									\n"
    "	jmp 1f								\n"
    "1:									\n"
    "	.code32								\n"
    "									\n"
    "	mov $0x2BADB002, %%eax						\n"
    "									\n"
    "	jmp *%%edi							\n"
    "									\n"
    "	/* GDT. */							\n"
    "	.p2align 4							\n"
    "gdt:									\n"
    "	.byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00		\n"
    "	.byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00		\n"
    "	/* Code */							\n"
    "	.byte 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x9A, 0xCF, 0x00		\n"
    "	/* Data */							\n"
    "	.byte 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x92, 0xCF, 0x00		\n"
    "									\n"
    "gdtdesc:								\n"
    "	.word 31							\n"
    "gdtaddr:								\n"
    "	.quad gdt							\n"
    "									\n"
    "idtdesc:								\n"
    "	.word 0								\n"
    "idtaddr:								\n"
    "	.quad 0								\n"
    "									\n"
    "	.align 16							\n"
    "vector:								\n"
    "	.long 0								\n"
    "	.long 0x10	/*CS*/						\n"
    ".code64								\n"
    : : "a" ((uint32_t) entry), "b" ((uint32_t) (size_t) &mb_info));

}
